### PR TITLE
Adds checkbox for disabling user tracking in app analytics

### PR DESCRIPTION
**Pull request by tonytlwu**
image

### CODE REVIEW

**Comment by tonytlwu** [comment]
@squallstar I've got the interface ready here. How can the `build.js` or `fliplet-core` analytics code be changed to disable user tracking?

**Comment by squallstar** [comment]
@tonytlwu didn't you just changed it in build.json not to run the code when the tracking is disabled? However, that would not have been necessary because of this: https://github.com/Fliplet/fliplet-api/blob/master/public/assets/fliplet-core/1.0/core.js#L1824-L1827

**Comment by tonytlwu** [comment]
@squallstar I should clarify. Disabling user tracking means that we will still track pageviews and events, but we won't be adding any user information to the logs.

**Comment by squallstar** [comment]
@tonytlwu so... tracking doesn't get disabled, it just keeps tracking but anonymously? That's not how this is meant to work as far as I know. As a matter of fact, when tracking is disabled GA is also disabled completely (it doesn't even get injected in the page https://github.com/Fliplet/fliplet-api/blob/master/public/assets/fliplet-core/1.0/core.js#L2357-L2362)

**Comment by tonytlwu** [comment]
@squallstar Pushed https://github.com/Fliplet/fliplet-widget-analytics/pull/2/commits/3d6826ccfede7f650c2bf9b984addd192dded8df to remove the check of `Fliplet.Analytics.isTrackingEnabled`

**Comment by tonytlwu** [comment]
@squallstar I'll clarify again. Disabling analytics is one thing -- we've already got that covered.

We need to give app admins the control to continue tracking app usage while making it anonymous. This is something more granular and was [mentioned in the spec](https://docs.google.com/document/d/13EYgWrUfSNmsIHG0eWKakWMPEZeEojxY76iiNZVP3Sc/edit#).

So far I've added an interface and a configuration `data.trackUsers` but am uncertain how to best use that to disable this https://github.com/Fliplet/fliplet-api/blob/master/public/assets/fliplet-core/1.0/core.js#L1836-L1838. I've got a few ideas but thought it's better to come from you.

**Comment by tonytlwu** [comment]
@squallstar I gave it a go here https://github.com/Fliplet/fliplet-api/pull/2791

**Comment by squallstar** [comment]
@tonytlwu I see it now, yes what you added works perfectly.

**Pull request merged**
